### ISSUE TITLE
Quel programme de test faut-il garder ?

### ISSUE THREAD

**Issue by AlexP20000** [AlexP20000/borne-satisfaction#24]
Dans le répertoire Programmation/Microcontroleur :

1. Il y a 1 fichier **test_borne_satisfaction.ino** dans le répertoire  du même nom
2. il y a le même fichier dans tests/test_borne_satisfaction

Quel fichier faut-il garder ?

**Comment by laurentuof** [comment]
J'ai réorganisé. Ce qui reste est correct.
