### ISSUE TITLE
Passer en define l'initialisation du serial print

### ISSUE THREAD

**Issue by MathieuCariou** [AlexP20000/borne-satisfaction#4]
Dans la branche Programmation Microcontrolleur : 

Dans borne de satisfaction.ino,
  // initialisation de la liaison série.
  //
  if ( ModeDebug ) {
    Serial.begin(115200);
    delay(1000);  // On attend que le port serie soit initialisé
    DEBUG("OK, let's go ******************************************");
  }

utiliser un IFDEF DEBUG à la place de la fonction if( ... )  pour prendre moins de place en m
mémoire

**Comment by AlexP20000** [comment]
Mis à jour faite pour la prochaine livraison
